// client/src/ui/track-view.tsx
import * as React from 'react';
import { Track, getDistanceString } from '../domain/track';

import 'ol/ol.css';
// import ol from 'ol';
import Map from 'ol/map';
import View from 'ol/view';
import Tile from 'ol/layer/tile';
import OSM from 'ol/source/osm';
import LineString from 'ol/geom/linestring';
import Feature from 'ol/feature';
import Vector from 'ol/layer/vector';
import SourceVector from 'ol/source/vector';
const proj = require('ol/proj').default;
// import * as SourceVector from 'ol/source/vector';

import Stroke from 'ol/style/stroke';
import Style from 'ol/style/style';
import { SpeedChart } from './speed-chart';
import { getDurationString } from '../utilities/duration';
import { LapsView } from './laps-view';
// import ol from 'ol';
// import * as proj from 'openlayers';
// import { Coordinate } from 'openlayers';

// import * as proj from 'ol/proj';

// interface Proj {
//   fromLonLat(x: number[]): Coordinate;
// }

const drawMap = (track: Track, target: string) => {

  const coords = track.records.map((record) => {
    return [record.posLong, record.posLat];
  }) as [number, number][];

  const lineString = new LineString(coords);
  lineString.transform('EPSG:4326', 'EPSG:3857');

  const feature = new Feature({
    geometry: lineString,
    name: 'line'
  });

  const lineStyle = new Style({
    stroke: new Stroke({
      color: '#0000ff',
      width: 4
    })
  });

  const vector = new Vector({
    source: new SourceVector({
      features: [feature]
    }),
    style: lineStyle
  });

  // tslint:disable-next-line
  console.log(vector);

  // console.log(proj);

  return new Map({
    layers: [
      new Tile({
        source: new OSM()
      }),
      new Vector({
        source: new SourceVector({
          features: [feature]
        }),
        style: lineStyle
      })
    ],
    target: target,
    view: new View({
      center: proj.fromLonLat([
        (track.activityBounds.longMin + track.activityBounds.longMax) / 2,
        (track.activityBounds.latMin + track.activityBounds.latMax) / 2,
      ]),
      resolution: 20
    })
  });
};

interface Route {
  match: {
    path: string;
    params: {
      trackName: string;
    }
  };
  location: {};
  history: {};
}

type TrackViewState = {
  track: Track|null
};

type TrackMapProps = {
  track: Track
};

class TrackMap extends React.Component<TrackMapProps> {
  map: Map|null = null;

  renderMap = () => {
    this.map = drawMap(this.props.track, 'map');
    // this.map = new Map({
    //     view: new View({
    //         center: [0, 0],
    //         zoom: 1
    //     }),
    //     layers: [
    //         new Tile({
    //           source: new OSM()
    //             // source: new ol.source.OSM()
    //         })
    //     ],
    //     target: 'map'
    // });
  }
  render() {
    return (
      <div>
        <div id="map" style={{width: '100%', height: '600px'}} ref={this.renderMap} />
      </div>
    );
  }
}

export class TrackView extends React.Component<Route, TrackViewState> {
  state = {
    track: null
  };

  componentWillMount() {
    const url = `//localhost:8090/api/tracks/file?filePath=${encodeURIComponent(this.props.match.params.trackName)}`;
    fetch(url).then(resp => {
      resp.json().then((track: Track) => {
        track.summary.startTime = new Date(track.summary.startTime);
        track.summary.endTime = new Date(track.summary.endTime);

        track.records.forEach((record) => {
          record.timestamp = new Date(record.timestamp);
        });

        this.setState({
          track
        });
      });
    });
  }

  render() {
    let {track} = this.state;

    if (track === null) {
      return (<p>Loading</p>);
    }

    const t = (track as Track);
    const durationStr = getDurationString(t.summary.startTime, t.summary.endTime);
    const distance = getDistanceString(t.summary);
    const durationSeconds = (t.summary.endTime.getTime() - t.summary.startTime.getTime()) / 1000;
    const avSpeedMetresPerSecond = t.summary.totalDistance / durationSeconds;
    const avSpeedKph = (avSpeedMetresPerSecond * 3600 / 1000).toFixed(2);

    return (
      <div>
        {distance} in {durationStr} ({avSpeedKph} Km/h)
        <TrackMap track={track} />
        <LapsView track={track} />
        <SpeedChart track={track} />
      </div>
    );
  }
}

// client/src/app/ui/track-view.component.ts
import { Component, Input, ViewChild } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';

import 'rxjs/add/operator/switchMap';
import { of } from 'rxjs/observable/of';

import * as OpenLayers from 'openlayers';

import { TrackService } from '../service/track.service';
import { Track } from '../domain/track';
import { Lap } from '../domain/lap';

@Component({
  selector: "track-view",
  template: `
  <div *ngIf="!isDataLoaded">
    Loading
  </div>
  <div *ngIf="isDataLoaded">
    {{ track.summary.getDistanceString() }} in {{ track.summary.getDurationString() }}
  </div>
  <div #map></div>
  <div *ngIf="areLapsLoaded">
    <table class="table">
      <thead>
        <tr>
          <th>Duration</th>
          <th>Lap Distance</th>
          <th>cumulative Distance</th>
          <th>Altitude Gain</th>
          <th>Start Altitude</th>
          <th>End Altitude</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let lap of laps">
          <td>{{ lap.getDurationString() }}</td>
          <td>{{ lap.distanceInLapMetres }}m</td>
          <td>{{ lap.cumulativeDistanceMetres }}m</td>
          <td>{{ lap.endAltitude - lap.startAltitude }}m</td>
          <td>{{ lap.startAltitude }}m</td>
          <td>{{ lap.endAltitude }}m</td>
        </tr>
      </tbody>
    </table>
  </div>
  `
}) //startTimestamp, public endTimestamp: Date, public distanceInLapMetres, public cumulativeDistanceMetres, public startAltitude, public endAltitude:
export class TrackView {
  private track: Track;
  private map: OpenLayers.Map;
  private laps: Lap[];

  @ViewChild("map")
  private mapContainer;

  private isDataLoaded = false;
  private areLapsLoaded = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private trackService: TrackService
  ){}

  ngOnInit() {
    this.route.paramMap.switchMap((params: ParamMap) => {
      let trackName = params.get('name');
      return of(trackName);
    }).subscribe((trackName: string) => {

      const fetchTrackObserable = this.trackService.fetchTrack(trackName);
      fetchTrackObserable.subscribe((track) => {
        this.track = track;
        this.isDataLoaded = true;
        this.drawMap();
      }, (err) => {
        throw err;
      });

      const fetchLapsObservable = this.trackService.fetchLaps(trackName);
      fetchLapsObservable.subscribe((laps) => {
        this.laps = laps;
        this.areLapsLoaded = true;
      });
    });
  }

  private drawMap() {
    const coords = this.track.records.map((record) => {
      return [record.posLong, record.posLat];
    }) as [number, number][];

    const lineString = new OpenLayers.geom.LineString(coords);
    lineString.transform('EPSG:4326', 'EPSG:3857');

    const feature = new OpenLayers.Feature({
      geometry: lineString,
      name: "line"
    });

    const lineStyle = new OpenLayers.style.Style({
      stroke: new OpenLayers.style.Stroke({
        color: '#0000ff',
        width: 4
      })
    });

    this.map = new OpenLayers.Map({
      layers: [
        new OpenLayers.layer.Tile({
          source: new OpenLayers.source.OSM()
        }),
        new OpenLayers.layer.Vector({
          source: new OpenLayers.source.Vector({
            features: [feature]
          }),
          style: lineStyle
        })
      ],
      target: this.mapContainer.nativeElement,
      view: new OpenLayers.View({
        center: OpenLayers.proj.fromLonLat([
          (this.track.activityBounds.longMin + this.track.activityBounds.longMax) / 2,
          (this.track.activityBounds.latMin + this.track.activityBounds.latMax) / 2,
        ]),
        resolution: 20
      })
    });
  }
}
